travis:
  secure:
    BINSTAR_TOKEN: TuzvrXwx9AbeGp2WYvVvZ6PdPUOXIDCd9RwFtr0bSxhPhrHFTDIvtFxGEzuamhj8FvJEobPAY10RwH2v5wrEoP1zSi0n3pfcb9vC3uXK2wsDNVHQ6YPpklHG7kwR0NmBSjhO7/Uqf1FPQDj3yn8ZSDj+QUN7TzaM5fr/NhfkJ8JAK7+q4G5Za1Sy5ZJk/MXzOrG1I9rkfoAKmtqqutoUAraBwlnGA4hylC2e1Zsb1t1YOCWtDY/JjEtIn3tMLNrSFs31uNQTbki3b87MJXWKi/MoasmaSK83GBbTbP/iR+5weR2TRWXVAuDhaj89p1VAbm+aJJ4M9ncHG2A+RTUygXIVMvOHWIcAslzyVDctwZvAvWddlz2v/pw4gGQwfT3a3TIfmV1qxZ1Q4BrigBKQom7JAQosW+9odUBSYz806VLW1QyRkFeK3ipmOZymqE9j5ZWJiIkQuHb2+oZN5CkCPraRPyyT3DJ/rQwZm7z411HB7qHM8nRWX7MuN15nj01ezU1o6rmMpbThT4705X8EmB28lftKqJrOEAO3yWPB4lB0AhtFcrbJkZclHDBB9xFAfQI1GtgLoeC6DECMEHnBcfAEcVb7d9udiEazsp8ZvpilEdbEViaNwUu2xn+TAA3Z6WKC+LxsQs7IAoK/+mUu+xr4UZ1CNscwHCytpIs8Lcs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
