travis:
  secure:
    BINSTAR_TOKEN: BVWeYQ1TpMn89zLVX0YbIPD/167174ie4p2oHb1mNitDtOVhnUoHZLF8rvK41wSlUxmw6K3CqZqkpi3jYEXwiko2kYRob74kHBFBO3LPDwS0dzc8R2FjGPY7CAumHemMieSYBN71eWZy06VGrG01G4/bb1tnQ7PNROdqWcZPzJbvm8J+v9RpGgfaynTyFfTIUwh0wuBB9Z1KbJLQr0MZrdLLddi21nqNLUm4NIXtUeY0P4lC8EoXmDC4KBwExbjNZr+iiuV2sGkCoD0G/eBtZvgnwg/WfegwBenJin53f+xA3QePgMbp25TrZwsUBwXOGiMpf0NAfBZYNKRPDnLOMt+2xud2WtTfNBr1j7fdDP9VZq8z09gSpzptFMW22gHtfgKIuvgqDY8Qrbj1lcXQE+ewfrVzKLLnwRxd+DQ1NTpNcWzENdp6qRWvBWua8dUBtXfuxyya9/r3O4S/kWeLmeApEUs47py2MKUt1oGdlTblp+duCeQpjJWIrSMT/Hcfj6W4nzF+7TQt92dwhP2RmyzGsitEq6sR4xfhCAOM9mKaM5EmOl/OXbHtM98j+wEzQ/gn7O94Xf8Cr1GS8DmbIuyObxi0qN/lchSIO+WQQ25g7nlwk9dK0Yf9AyOVIpZj11lukTGNefNnou/NqBU8vbsbQ73fxP1ExLTsxocCJ+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
