travis:
  secure:
    BINSTAR_TOKEN: RestE2Lq48XFcZvmT6ll6gDcTMqWDDbFsLKmEmefZDaZqjJSQ5GFIj07JWEt3hzRntH2Z4V6OzJrgyxWB4NLtcgFhjEpBLOsPU7Fh/V9zsjnVrs2weBAcdr/tB4XzrpMkVAG6f4h71xCeMhHLSufO+qhdGsCvWdq8AIbr/vfL6Lr/KWJPRb+pcOM+/jtnnvhWuebHwL38Ja+mQz6cFEV+oUXFhCRgsUQYtwD6T85lHCISWMAJQ0k+KEeWwAh7P63oWBwojsxvJZpxJSTxvmsclDph+69HriTLqfCg6Ja/WgZ38amk02YTJxnlr6YegvD1at0RfJMIN+oEAeBZA0MV8fRLblwkIfBKpfoA7QvEiHmS30OxQjglH+Ax02amxJnQgvLYR0u9hC1sQf6eT6Uyr50OKiqgZjyX2/25rKJhFKuUuTc1brfeerzSIze7DZs/MQ7luI3t4ZUAPvRHyvo++JUgspemG+f8Ofml1ZgF+RZ08qs41xzzLTULjNy18kTLFq2Cu1HBMXdlW4/mfHyUotpj2sudDIXuiCHlNEpwfJ+FKFWYfxUDZVEmQjZfYMltsKriVmEITYw3uWdPCJwusCGMsDXnDLcd9zCJPaLNp4G6haIvjCAHZ3URV8iitdSqaAu68sRxbjCJrwN5R0kNquL3b23BCSGVy4VQha3AnI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
